### ISSUE TITLE
Minimal starting plot

### ISSUE THREAD

**Issue by sandrappio** [dgbowl/dgpost#23]
Plot in 3 vertical, aligned windows the data as a function of time. See sketch attached!

Window 1:
Voltage WE vs time

WIndow 2
FE of main products vs time
Main products means H2, CO, CH4, C2H4, HCOOH, CH3CH2OH

Window 3
Corollary info, gas flow and electrolyzer
 temperature vs time

![signal-2022-03-25-164159_001](https://user-images.githubusercontent.com/77737818/160154154-b31b0389-45b9-4606-8857-8e203e7654da.jpeg)

**Comment by PeterKraus** [comment]
Thanks, that makes a lot of sense. Do you want to have the graphs the same vertical size? Something very similar has been implemented in the "draft" PR by @ileu in #5, if the above is all you need (for now), it should be possible to sort it in a matter of days.

**Comment by sandrappio** [comment]
Yeah I think that would work for a first draft no? We can chat in person
also but I think it's useful for a start to be able to quickly see these
data this way. Kinda showcase the potential of the data manageemnt

**Comment by PeterKraus** [comment]
Basic plotting has been implemented in #5. After I merge the new schema validator in (#24), it should be possible to do more customised plot (supply axis limits etc) via the yaml file. I'll try to make a test case like your 3-panel figure above in a next PR.

**Comment by PeterKraus** [comment]
This has been implemented in #24, see [this figure](https://github.com/dgbowl/dgpost/blob/4c5b53a42ffe1f8139869d439f6519c8aa95578d/tests/test_realworld/ts0/ref.plot.png) which lives at `tests/test_realworld/ts0/ref.plot.png`.
